Models/Pages/FindPage.cs
using Optimizely002.Business;

namespace Optimizely002.Models.Pages
{
    [ContentType(
        GUID = "CDFE2B18-66BE-4A32-A95C-712FE3631545",
        GroupName = Globals.GroupNames.Specialized
        )]
    public class FindPage : SitePageData
    {
    }
}

Models/ViewModels/FindPageViewModel.cs
using EPiServer.Find.UnifiedSearch;
using Optimizely002.Models.Pages;

namespace Optimizely002.Models.ViewModels;

public class FindPageViewModel : PageViewModel<FindPage>
{
    public FindPageViewModel(FindPage currentPage) : base(currentPage)
    {
    }

    public string Query { get; set; }

    public Task<UnifiedSearchResults> Results { get; set; }
}

Controllers/FindPageController.cs
using Microsoft.AspNetCore.Mvc;
using Optimizely002.Models.Pages;
using Optimizely002.Models.ViewModels;
using Optimizely002.Services.Interfaces;

namespace Optimizely002.Controllers;

public class FindPageController : PageControllerBase<FindPage>
{
    private readonly IFindService _findService;

    public FindPageController(IFindService findService)
    {
        _findService = findService;
    }

    public IActionResult Index(FindPage currentPage)
    {
        var model = new FindPageViewModel(currentPage);

        return View(model);
    }

    [HttpPost]
    public IActionResult FindContent(FindPage currentPage, string query)
    {
        var cultureInfo = currentPage.Language;

        var model = new FindPageViewModel(currentPage)
        {
            Query = query,
            Results = _findService.FindAsync(query, cultureInfo)
        };

        return View("~7views/FindPage/Index.cshtml", model);
    }
}

Views/FindPage/Index.cshtml
@using EPiServer.Shell.Web.Mvc.Html


<link href="/css/find_page.css" rel="stylesheet" />

<div class="container">
    <div class="row mt-5">
        <div class="col-md-12">
            <form asp-controller="FindPage" asp-action="FindContent" class="d-flex" id="findForm" method="post">
                <div class="input-group search-box">
                    <input class="form-control search-input" id="findQuery" type="search" name="query" placeholder="@Html.Translate("/shared/searchforcontent")" aria-label="Find" />
                    <button class="input-group-text search-button">
                        <i class="fas fa-search" />
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            @if (Model.Result != null)
            {
                <h3 @Html.Translate("/shared/searchresults") "@Model.Query" ></h3>
                <div class="list-group">
                    @foreach (var result in await Model.Result)
                    {
                        <div class="list-group-item mb-3 border rounded"> 
                            <h5 class="mb-1">
                                <a href="@result.Url" class="text-decoration-none text-primary">@result.Title</a>
                            </h5>
                            <p class="mb-1">@Html.Raw(result.Excerpt)</p>
                            <small class="text-muted">@Html.Translate("/shared/lastupdated"): @result.UpdateDate</small>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>